name: Manual Workflow

on: 
  push:
    branches: [ "main" ]
  #workflow_dispatch:
  #pull_request:
  #  branches: [ "main" ]

jobs:
  upload:
    name: Upload file
    runs-on: ubuntu-latest

    steps:
      - run: echo "${GITHUB_ACTION_PATH}"
      - run: echo "Hello, world!" > file.txt
      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt

  download:
    name: Download file
    runs-on: ubuntu-latest
    needs: upload
    
    steps:
      - run: echo "${{ github.action_path }}"
      - uses: actions/download-artifact@v4
        with:
          name: file
      - run: cat file.txt # how to use dynamic name from upload?
