name: Manual Workflow

on: 
  #push:
  #  branches: [ "main" ]
  #workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  check_suite:
    types: [completed]

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
