name: Manual Workflow

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
